### ISSUE TITLE
Syntax highlighting problem

### ISSUE THREAD

**Issue by mrmccormack** [bchetty/jekyllBasic#2]
I can never seem to get the syntax highlighting to work on a hosted GitHub Jekyll site.

I have forked your jekyllBasic
and in 

``` html
<strong>hello world</strong>
```

But 

The preview of the .md file looks good, in color, but not on my site
http://mrmccormack.me/aboutme/

Any suggestions?
Thanks
Rob

By the way, thanks for the jekyllBasic template! Very instructive.

**Comment by bchetty** [comment]
@mrmccormack 

That should work, as the 'preview' shows it correctly. Anyways, please try this and see if it works:

> {% highlight html%}
> `<strong>hello world</strong>`
> {% endhighlight %}

**Comment by mrmccormack** [comment]
Hey thanks for fast action...
No luck...

## My config

https://github.com/mrmccormack/mrmccormack.github.io/blob/master/_config.yml
same as yours

## My About:

https://github.com/mrmccormack/mrmccormack.github.io/blob/master/aboutme/index.md

I'm using GitHub to write the pages with Jekyll, not running locally.

I've tried for a few days with lots of templates and suggestions... and nothing I do seems to work. I know it is the new version of Jekyll.

I want to write a tutorial on Jekyll on GitHub, It's amazing and a great way to learn things.

Rob

**Comment by mrmccormack** [comment]
This must be a GitHub/Jekyll issue: 

Nothing seems to highlight.

I added:

``` yml
# Set these options as you need (For more information, check Jekyll's site)
timezone: "Europe/Berlin"
# markdown: kramdown
# highlighter: rouge
permalink: /blog/:title
paginate: 5

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
```

but no luck at all.

Thanks for help.
Rob

**Comment by bchetty** [comment]
@mrmccormack

I thought the Jekyll plugin generates the required CSS, but it looks like it doesn't. Also, I didn't put much thought into this, as I am using "Github Gists" for most of my posts. Anyways, after 'inspecting' the page ,now I know that the necessary CSS classes were missing for "Syntax Highlighting". I found a off-the-shelf CSS file [here](https://github.com/mojombo/tpw/blob/master/css/syntax.css) and copied it to my project folder and included it in the "Head" part of the page. Now, it's working.

Also, the configuration in _config.yml should be:

```
markdown: kramdown
#highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
```

The below listed points tell you how to get it working:

1) Create a new CSS file called '[syntax.css](https://github.com/bchetty/jekyllBasic/blob/2827a97abde71e28c1f37930931818f020365f53/assets/css/syntax.css)' and copy/move it to your CSS/assets project folder.

2) Include the CSS file in the "HEAD" section of HTML page. In my project, it is added to the head.html file in the "_includes" folder, as shown below:

```
<!-- Styles for 'Syntax Highlighting' of code -->
<link href="{{ site.baseurl }}/assets/css/syntax.css" rel="stylesheet">
```

3) Correct the _config.yml configuration:

Replace the below 2 lines:

```
markdown: kramdown
highlighter: rouge
```

With:

```
markdown: kramdown
#highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
```

PS: You can also see the changes (Commits on Sep 26, 2016) in my Github projects [jekyllBasic](https://github.com/bchetty/jekyllBasic/commits/master) and [jekyllBasicBlog](https://github.com/bchetty/jekyllBasicBlog/commits/master).

Thanks for reporting the problem! :+1:
